name: flutter_html_iframe
description: This extension package allows the <iframe> tag to be rendered using the flutter_html package
version: 3.0.0-beta.2f1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html:
    git:
      url: https://github.com/tomeko-atmoapps-com/flutter_html
      ref: 6edd62f686824fdca1a6462bb8b2a6d1fa2f8baf
  webview_flutter: '>=4.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - iframe
  - layout
  - flutter_html
